AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template for IAM User"

Resources:
  # My IAM User
  MyIAMUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "AminCF"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  # My IAM Group
  MyIAMGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "AminGroup"

  # Attach IAM User to Group
  AttachUserToGroup:
    Type: "AWS::IAM::UserToGroupAddition"
    Properties:
      GroupName: !Ref MyIAMGroup
      Users:
        - !Ref MyIAMUser
